bucket:
  strip: 1

packages:
  - name: ge2020
    actions:
      - name: news
      - name: timeseries
      - name: counties
      - name: exitpolls
      - name: state_counties
      - name: resources
      - name: divisions
        environment: $(GOOGLE_CIVIC_API_TOKEN)
      - name: elections
        environment: $(GOOGLE_CIVIC_API_TOKEN)
      - name: reps
        environment: $(GOOGLE_CIVIC_API_TOKEN)
      - name: voterinfo
        environment: $(GOOGLE_CIVIC_API_TOKEN)
